#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: default
  labels:
    app: nodejsapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejsapp
      tier: frontend
      version: 1.0.0
#pod tempalte
  template:
    metadata:
      labels:
        app: nodejsapp
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: nodejs-container
        image: 335871625378.dkr.ecr.eu-west-2.amazonaws.com/karo-march-repo:20
        ports:
        - containerPort: 8080
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejsapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nodejsapp

